function run_blockB_100trials_onebatch_v72(profile, snr_db, batch_idx, varargin)
%RUN_BLOCKB_100TRIALS_ONEBATCH_V72 Run one small Block-B Monte-Carlo batch.

p = inputParser;
addRequired(p, 'profile', @(x) ischar(x) || isstring(x));
addRequired(p, 'snr_db', @(x) isnumeric(x) && isscalar(x));
addRequired(p, 'batch_idx', @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'save_dir', 'paper_final_blockB_100trials_v72', @ischar);
addParameter(p, 'batch_trials', 1, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'samples', 80000, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'trainLen', 12000, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'baud', 26.5625e9, @(x) isnumeric(x) && isscalar(x) && x > 0);
parse(p, profile, snr_db, batch_idx, varargin{:});
opt = p.Results;

profile = char(opt.profile);
batch_dir = fullfile(opt.save_dir, sprintf('_batches_%s_snr%02d', profile, opt.snr_db), ...
    sprintf('batch%03d', opt.batch_idx));
batch_csv = fullfile(batch_dir, 'ieee8023ck_markov_sweep_summary.csv');
if exist(batch_csv, 'file') == 2
    fprintf('[blockB100_onebatch] resume %s\n', batch_csv);
    return;
end

addpath(genpath(pwd));
fprintf('[blockB100_onebatch] profile=%s snr=%g batch=%d trials=%d samples=%d\n', ...
    profile, opt.snr_db, opt.batch_idx, opt.batch_trials, opt.samples);

run_paper('8023ck_sparam', ...
    'trials', opt.batch_trials, ...
    'snr', opt.snr_db, ...
    'max_cases', 6, ...
    'baud', opt.baud, ...
    'run_static', false, ...
    'run_markov', false, ...
    'run_markov_sweep', true, ...
    'p_stay', local_profile_pstay(profile), ...
    'markov_nsym', opt.samples, ...
    'markov_trainLen', opt.trainLen, ...
    'markov_twochain', true, ...
    'markov_twochain_noise_scale', 1.25, ...
    'markov_twochain_imp_prob', 0, ...
    'markov_twochain_imp_alpha', 0, ...
    'markov_nb', 4, ...
    'markov_smnlms_tau', 0.35, ...
    'markov_smnlms_beta', 0.015, ...
    'markov_use_adaptive_tau', true, ...
    'markov_tau_calib', 0.5, ...
    'markov_use_transition_gate', false, ...
    'seed_offset', 1000000*opt.batch_idx + 1000*round(opt.snr_db), ...
    'plot', false, ...
    'fig_visible', 'off', ...
    'save_dir', batch_dir);
end

function pstay = local_profile_pstay(profile)
switch lower(char(profile))
    case 'slow'
        pstay = 0.985;
    case 'medium'
        pstay = 0.970;
    case 'fast'
        pstay = 0.955;
    otherwise
        error('Unknown Block B profile: %s', char(profile));
end
end
