% run_blockA_hybrid_launcher.m
% Config: SNR 15-25, 1e6 samples, 10 trials (uniform — no tier-high).
% Eye diagram + BER Monte Carlo plot generated after BER run completes.
addpath(genpath(pwd));

% ---- BER Monte Carlo SNR 15-25 ----
run_final_blockA_hybrid_resume_v72( ...
    'snr_low',      15:25, ...
    'trials_low',   10,    ...
    'samples_low',  1e6,   ...
    'snr_high',     [],    ...
    'trials_high',  10,    ...
    'samples_high', 1e6,   ...
    'save_dir',     'paper_final_BlockA_hybrid_v72', ...
    'fig_visible',  'off');

% ---- Eye diagram at SNR=25 ----
run_blockA_eye_diagram_snr25( ...
    'snr_db',    25, ...
    'save_dir',  'paper_final_BlockA_hybrid_v72', ...
    'fig_visible', 'off');

% ---- BER Monte Carlo curve SNR 15-25 ----
run_blockA_ber_plot( ...
    'save_dir',    'paper_final_BlockA_hybrid_v72', ...
    'snr_range',   15:25, ...
    'fig_visible', 'off');
