function run_final_overnight_start()
%RUN_FINAL_OVERNIGHT_START  Launcher used for detached overnight MATLAB run.

addpath(genpath(pwd));
run_final_overnight_v72( ...
    'save_dir', 'paper_final_overnight_v72', ...
    'snr', 15:1:30, ...
    'blockA_trials', 10, ...
    'blockA_samples', 1e7, ...
    'blockA_trainLen', 12000, ...
    'blockB_trials', 10, ...
    'blockB_samples', 80000, ...
    'blockB_trainLen', 12000, ...
    'blockC_trials', 10, ...
    'blockC_samples', 80000, ...
    'blockC_trainLen', 8000, ...
    'run_extra_tracking_mc', false);
end
