function run_blockC_batched_background_entry_v72()
%RUN_BLOCKC_BATCHED_BACKGROUND_ENTRY_V72 Entry point for background MATLAB.
if ~exist('paper_final_BlockC_100trials_v72', 'dir')
    mkdir('paper_final_BlockC_100trials_v72');
end
fid = fopen(fullfile('paper_final_BlockC_100trials_v72', 'blockC_entry_started.txt'), 'a');
if fid > 0
    fprintf(fid, '[%s] entry started\n', datestr(now, 31));
    fclose(fid);
end
addpath(genpath(pwd));
outC = run_final_blockC_batched_resume_v72( ...
    'snr', 15:30, ...
    'trials', 100, ...
    'batch_trials', 5, ...
    'samples', 80000, ...
    'trainLen', 8000, ...
    'save_dir', 'paper_final_BlockC_100trials_v72', ...
    'fig_visible', 'off');
save(fullfile('paper_final_BlockC_100trials_v72', 'BlockC_batched_background_out.mat'), ...
    'outC', '-v7.3');
end
