function fpaths = plot_ck_stress_eye_split(out, opts, save_format)
%PLOT_CK_STRESS_EYE_SPLIT  Split CK-stress eye diagrams into one 3x3 figure per profile.
%
% v72:
%   * Uses the existing out.eye_bank generated by run_paper('ck_stress').
%   * Adds Eye Height and approximate Eye Width annotations in every panel.
%   * Exports ck_eye_height_width_snr22_v72.csv for table/report writing.
%   * Produces four separate profile figures by default:
%       ck_eye_isi_awgn_snr22_split_v72
%       ck_eye_isi_xtalk_awgn_snr22_split_v72
%       ck_eye_isi_jitter_awgn_snr22_split_v72
%       ck_eye_dirty_full_snr22_split_v72
%   * Each figure has a 3x3 layout:
%       Before EQ + Algorithm 2 + Algorithm 1 + NLMS + SM-sign
%       + Liu SS-LMS + Liu TA-SS-LMS + Cui + Chen.
%   * Oracle is intentionally omitted from the plotted panels.
%   * Uses common y-limits across all split eye figures for fairer visual comparison.
%   * Does not normalize each method independently. Only symbol-rate traces are
%     converted to an eye-like waveform through a common raised-cosine pulse.
%
% Usage after running ck_stress:
%   out = run_paper('ck_stress', 'save_dir', 'paper_figs', 'format', 'png');
%   plot_ck_stress_eye_split(out, 'paper_figs', 'png');
%
% This plotter is called automatically by plot_ck_stress.m in v72.

if nargin < 2 || isempty(opts)
    opts = struct();
end
if nargin < 3 || isempty(save_format)
    save_format = 'png';
end
if ischar(opts) || isstring(opts)
    save_dir = char(opts);
    opts = struct('save_dir', save_dir, 'save_format', char(save_format), 'dpi', 300, 'fig_visible', 'on');
end
if ~isfield(opts,'save_dir') || isempty(opts.save_dir), opts.save_dir = 'figs'; end
if ~isfield(opts,'save_format') || isempty(opts.save_format), opts.save_format = 'png'; end
if ~isfield(opts,'dpi') || isempty(opts.dpi), opts.dpi = 300; end
if ~isfield(opts,'fig_visible') || isempty(opts.fig_visible), opts.fig_visible = 'on'; end
if ~exist(opts.save_dir,'dir'), mkdir(opts.save_dir); end

fpaths = {};

if ~isstruct(out) || ~isfield(out,'eye_bank') || isempty(out.eye_bank)
    warning('plot_ck_stress_eye_split:no_eye_bank', 'out.eye_bank is missing. Split eye plots were skipped.');
    return;
end

eye_bank = out.eye_bank;
if ~isfield(eye_bank,'profiles') || ~isfield(eye_bank,'methods') || ~isfield(eye_bank,'signals')
    warning('plot_ck_stress_eye_split:bad_eye_bank', 'out.eye_bank does not contain the required fields. Split eye plots were skipped.');
    return;
end

profiles = eye_bank.profiles;
methods  = eye_bank.methods;
nprof    = numel(profiles);
nmeth    = numel(methods);

if isfield(eye_bank,'snr_ref') && ~isempty(eye_bank.snr_ref)
    snr_ref = eye_bank.snr_ref;
else
    snr_ref = local_last_snr(out);
end
if isempty(snr_ref) || ~isfinite(snr_ref), snr_ref = 22; end

% Plot order: one input panel + all stored method panels.
panel_titles = [{'Before EQ'}, local_short_method_names(methods)];

% Common eye rendering parameters.
sps = 16;
g = rc_pulse(0.5, sps, 8);

% Precompute eye waveforms and global y-limit across all profiles/methods.
wave_rx = cell(nprof,1);
wave_m  = cell(nprof,nmeth);
all_wave = [];
for pi = 1:nprof
    if isfield(eye_bank,'rx_before') && numel(eye_bank.rx_before) >= pi
        wave_rx{pi} = local_symbol_to_eye_waveform(eye_bank.rx_before{pi}, g, sps);
        all_wave = local_append_finite(all_wave, wave_rx{pi});
    end
    for mi = 1:nmeth
        x = [];
        if size(eye_bank.signals,1) >= pi && size(eye_bank.signals,2) >= mi
            x = eye_bank.signals{pi,mi};
        end
        wave_m{pi,mi} = local_symbol_to_eye_waveform(x, g, sps);
        all_wave = local_append_finite(all_wave, wave_m{pi,mi});
    end
end

yl = local_common_ylim(all_wave);

% PAM4 thresholds, if amplitude alphabet is available.
thresholds = [];
if isfield(eye_bank,'A') && numel(eye_bank.A) >= 2
    A = sort(eye_bank.A(:));
    thresholds = 0.5*(A(1:end-1) + A(2:end));
end

% Colors: fixed, colorblind-friendly, with gray input trace.
pal = pal_ieee();
cols = local_eye_colors(pal, nmeth);
rx_col = [0.15 0.15 0.15];

for pi = 1:nprof
    profile = profiles{pi};
    fig = figure('Name', sprintf('CK split eye - %s', profile), ...
                 'Color','w', 'Visible', opts.fig_visible, ...
                 'Position',[80 60 1450 980]);
    tl = tiledlayout(3,3,'TileSpacing','compact','Padding','compact');

    title(tl, sprintf('CK-inspired eye diagrams: %s, SNR = %g dB', profile, snr_ref), ...
          'Interpreter','none', 'FontWeight','bold', 'FontSize', 14);

    % Panel 1: Before EQ.
    ax = nexttile; hold(ax,'on'); grid(ax,'on'); box(ax,'on');
    local_plot_eye_waveform(ax, wave_rx{pi}, sps, rx_col, 150, 0.22);
    local_draw_thresholds(ax, thresholds, yl);
    ylim(ax, yl); xlim(ax, [0 2]);
    met = local_lookup_eye_metric(eye_bank, pi, 1);
    title(ax, sprintf('%s\nBER=N/A | EH=%s | EW=%sUI', panel_titles{1}, ...
        local_fmt_metric(local_metric_field(met,'eye_height_5_95')), ...
        local_fmt_metric(local_metric_field(met,'eye_width_ui'))), ...
        'FontWeight','bold', 'FontSize', 9);
    xlabel(ax,'Time (UI)'); ylabel(ax,'Amplitude');
    set(ax,'FontSize',9);

    % Panels 2..9: benchmark methods stored in eye_bank.
    for mi = 1:nmeth
        ax = nexttile; hold(ax,'on'); grid(ax,'on'); box(ax,'on');
        local_plot_eye_waveform(ax, wave_m{pi,mi}, sps, cols{mi}, 150, 0.22);
        local_draw_thresholds(ax, thresholds, yl);
        ylim(ax, yl); xlim(ax, [0 2]);
        ber_val = local_lookup_ber(out, profile, snr_ref, methods{mi});
        met = local_lookup_eye_metric(eye_bank, pi, mi+1);
        title(ax, sprintf('%s\nBER=%s | EH=%s | EW=%sUI', panel_titles{mi+1}, local_fmt_ber(ber_val), ...
              local_fmt_metric(local_metric_field(met,'eye_height_5_95')), ...
              local_fmt_metric(local_metric_field(met,'eye_width_ui'))), ...
              'FontWeight','bold', 'FontSize', 9);
        xlabel(ax,'Time (UI)'); ylabel(ax,'Amplitude');
        set(ax,'FontSize',9);
    end

    % A short note in the lower margin; this avoids overloading subplot titles.
    annotation(fig, 'textbox', [0.06 0.005 0.90 0.035], ...
        'String', 'Oracle MSB is omitted. EH = min 5-95% vertical eye height; EW = approximate horizontal eye width in UI. Not IEEE compliance metrics.', ...
        'EdgeColor','none', 'HorizontalAlignment','center', 'FontSize', 9);

    try
        ieee_access_style(fig);
    catch
        % Styling is optional; keep plot generation robust.
    end

    fname = save_fig_helper(fig, opts.save_dir, sprintf('ck_eye_%s_snr%d_split_v72', profile, round(snr_ref)), opts);
    fpaths{end+1} = fname; %#ok<AGROW>
end

try
    local_write_eye_metrics_csv(out, eye_bank, opts.save_dir, snr_ref);
catch ME
    warning('plot_ck_stress_eye_split:metric_csv_failed', ...
        'Could not write eye metric CSV: %s', ME.message);
end
end

% =====================================================================
function snr = local_last_snr(out)
snr = [];
if isstruct(out) && isfield(out,'snr_list') && ~isempty(out.snr_list)
    snr = out.snr_list(end);
end
end

% =====================================================================
function names = local_short_method_names(methods)
names = methods;
for k = 1:numel(names)
    s = names{k};
    s = strrep(s, 'Algorithm 2', 'Alg. 2');
    s = strrep(s, 'Algorithm 1', 'Alg. 1');
    s = strrep(s, 'Cui ExtraTrees-HMM', 'Cui ExtraTrees');
    s = strrep(s, 'Chen single-pulse', 'Chen single-pulse');
    s = strrep(s, 'Liu TA-SS-LMS', 'Liu TA-SS-LMS');
    s = strrep(s, 'Liu SS-LMS', 'Liu SS-LMS');
    names{k} = s;
end
end

% =====================================================================
function xos = local_symbol_to_eye_waveform(x, g, sps)
if isempty(x)
    xos = [];
    return;
end
x = x(:);
x = x(isfinite(x));
if numel(x) < 4
    xos = [];
    return;
end
% Important: no per-method amplitude normalization here. This preserves
% amplitude differences between methods. The same raised-cosine pulse is
% applied to every trace solely to visualize a symbol-rate eye.
xos = conv(local_upsample_zeros(x, sps), g, 'same');
end

% =====================================================================
function y = local_upsample_zeros(x, sps)
y = zeros(numel(x)*sps,1);
y(1:sps:end) = x(:);
end

% =====================================================================
function outv = local_append_finite(outv, x)
if isempty(x), return; end
x = x(:);
x = x(isfinite(x));
if ~isempty(x)
    % Limit memory: keep a deterministic subset if very long.
    if numel(x) > 6000
        idx = round(linspace(1, numel(x), 6000));
        x = x(idx);
    end
    outv = [outv; x]; %#ok<AGROW>
end
end

% =====================================================================
function yl = local_common_ylim(x)
if isempty(x)
    yl = [-4 4];
    return;
end
x = x(:); x = x(isfinite(x));
if isempty(x)
    yl = [-4 4];
    return;
end
q = prctile(x, [0.5 99.5]);
if ~all(isfinite(q)) || q(2) <= q(1)
    m = max(abs(x));
    if isempty(m) || ~isfinite(m) || m == 0, m = 4; end
    yl = [-1.15*m, 1.15*m];
else
    pad = 0.12 * max(q(2)-q(1), eps);
    yl = [q(1)-pad, q(2)+pad];
end
% Do not clip nominal PAM4 levels if waveforms are near ideal levels.
yl(1) = min(yl(1), -3.5);
yl(2) = max(yl(2),  3.5);
end

% =====================================================================
function local_plot_eye_waveform(ax, xos, sps, color, max_traces, line_width)
if isempty(xos)
    text(ax, 0.5, 0.5, 'No trace', 'Units','normalized', ...
        'HorizontalAlignment','center', 'FontWeight','bold');
    return;
end
try
    eye_plot_reshape_fixed(xos, sps, 'max_traces', max_traces, ...
        'color', color, 'line_width', line_width);
catch
    % Fallback: simple direct segmentation.
    span = 2*sps;
    N = floor(numel(xos)/span);
    if N < 1, return; end
    X = reshape(xos(1:N*span), span, N);
    Nplot = min(N, max_traces);
    idx = round(linspace(1, N, Nplot));
    t = linspace(0, 2, span);
    plot(ax, t, X(:,idx), 'Color', color, 'LineWidth', line_width, 'HandleVisibility','off');
end
end

% =====================================================================
function local_draw_thresholds(ax, thresholds, yl)
if isempty(thresholds), return; end
for k = 1:numel(thresholds)
    th = thresholds(k);
    if isfinite(th) && th >= yl(1) && th <= yl(2)
        plot(ax, [0 2], [th th], ':', 'Color', [0.35 0.35 0.35], ...
            'LineWidth', 0.55, 'HandleVisibility','off');
    end
end
end

% =====================================================================
function ber = local_lookup_ber(out, profile, snr_ref, method_name)
ber = NaN;
if ~isstruct(out) || ~isfield(out,'table') || isempty(out.table)
    return;
end
T = out.table;
best_idx = [];
for k = 1:numel(T)
    if isfield(T(k),'profile') && strcmp(T(k).profile, profile) && ...
       isfield(T(k),'SNRdB') && abs(T(k).SNRdB - snr_ref) < 1e-9
        best_idx = k;
        break;
    end
end
if isempty(best_idx)
    return;
end
Tk = T(best_idx);
if ~isfield(Tk,'methods') || ~isfield(Tk,'BER')
    return;
end
mi = find(strcmp(Tk.methods, method_name), 1, 'first');
if isempty(mi) || mi > numel(Tk.BER)
    return;
end
ber = Tk.BER(mi);
end

% =====================================================================
function s = local_fmt_ber(x)
if isempty(x) || ~isfinite(x)
    s = 'N/A';
elseif x == 0
    s = '0';
else
    s = sprintf('%.3e', x);
end
end

% =====================================================================
function cols = local_eye_colors(p, nmeth)
base = {p.proposed, p.alg5, p.nlms, p.smsign, p.liu_ss, p.liu_ta, p.cui, p.chen};
if nmeth <= numel(base)
    cols = base(1:nmeth);
else
    cols = repmat(base, 1, ceil(nmeth/numel(base)));
    cols = cols(1:nmeth);
end
end


% =====================================================================
function met = local_lookup_eye_metric(eye_bank, pi, col)
met = struct();
if isstruct(eye_bank) && isfield(eye_bank,'metrics') && ...
        size(eye_bank.metrics,1) >= pi && size(eye_bank.metrics,2) >= col
    tmp = eye_bank.metrics{pi,col};
    if isstruct(tmp), met = tmp; end
end
end

% =====================================================================
function v = local_metric_field(met, fname)
v = NaN;
if isstruct(met) && isfield(met, fname)
    v = met.(fname);
end
end

% =====================================================================
function s = local_fmt_metric(x)
if isempty(x) || ~isnumeric(x) || ~isfinite(x)
    s = 'N/A';
elseif abs(x) >= 100
    s = sprintf('%.1f', x);
elseif abs(x) >= 10
    s = sprintf('%.2f', x);
else
    s = sprintf('%.3f', x);
end
end

% =====================================================================
function local_write_eye_metrics_csv(out, eye_bank, save_dir, snr_ref)
if ~isfield(eye_bank,'metrics') || isempty(eye_bank.metrics)
    return;
end
if ~exist(save_dir,'dir'), mkdir(save_dir); end
csv_path = fullfile(save_dir, sprintf('ck_eye_height_width_snr%d_v72.csv', round(snr_ref)));
fid = fopen(csv_path, 'w');
if fid < 0
    warning('plot_ck_stress_eye_split:csv_open_failed', 'Could not open %s for writing.', csv_path);
    return;
end
cleaner = onCleanup(@() fclose(fid));

fprintf(fid, 'Profile,Method,BER,EyeHeight_5_95,EyeWidth_UI,MinQ,MeasuredThresholdSER,Notes\n');
profiles = eye_bank.profiles;
if isfield(eye_bank,'metric_methods') && ~isempty(eye_bank.metric_methods)
    metric_methods = eye_bank.metric_methods;
else
    metric_methods = [{'Before EQ'}, eye_bank.methods];
end
for pi = 1:numel(profiles)
    profile = profiles{pi};
    for col = 1:numel(metric_methods)
        method = metric_methods{col};
        met = local_lookup_eye_metric(eye_bank, pi, col);
        if col == 1
            ber = NaN;
        else
            ber = local_lookup_ber(out, profile, snr_ref, eye_bank.methods{col-1});
        end
        fprintf(fid, '%s,%s,%s,%s,%s,%s,%s,%s\n', ...
            local_csv_escape(profile), local_csv_escape(method), ...
            local_num_csv(ber), ...
            local_num_csv(local_metric_field(met,'eye_height_5_95')), ...
            local_num_csv(local_metric_field(met,'eye_width_ui')), ...
            local_num_csv(local_metric_field(met,'min_q')), ...
            local_num_csv(local_metric_field(met,'symbol_error_with_measured_thresholds')), ...
            local_csv_escape('simulation audit metrics, not IEEE compliance'));
    end
end
fprintf('[plot_ck_stress_eye_split] saved %s\n', csv_path);
end

% =====================================================================
function s = local_num_csv(x)
if isempty(x) || ~isnumeric(x) || ~isfinite(x)
    s = 'NaN';
else
    s = sprintf('%.12g', x);
end
end

% =====================================================================
function s = local_csv_escape(x)
x = char(string(x));
x = strrep(x, '"', '""');
s = ['"' x '"'];
end
