function out = run_smoke_all_figures_v72()
%RUN_SMOKE_ALL_FIGURES_V72 Small run that exports the final paper figure set.
%   This is a visual QA runner, not the final numerical benchmark.

addpath(genpath(pwd));

root = fullfile(pwd, 'smoke_all_figures_v72');
if ~exist(root, 'dir'), mkdir(root); end
log_file = fullfile(root, 'run_smoke_all_figures_v72.log');
diary(log_file);
diary on;
cleanupObj = onCleanup(@() diary('off')); %#ok<NASGU>

fprintf('\n[smoke_figs_v72] Started %s\n', datestr(now));
fprintf('[smoke_figs_v72] Output: %s\n', root);

out = struct();

try
    fprintf('\n[smoke_figs_v72] Block A mini Monte-Carlo BER.\n');
    out.blockA = run_paper('ber_severe', ...
        'trials', 20, ...
        'snr', [18 24 30], ...
        'plot', true, ...
        'fig_visible', 'off', ...
        'save_dir', fullfile(root, 'BlockA_mb_severe'));
catch ME
    out.blockA_error = ME;
    local_print_error('Block A', ME);
end

try
    fprintf('\n[smoke_figs_v72] Block B conservative C2M tracking.\n');
    out.blockB = run_paper('8023ck_sparam', ...
        'trials', 1, ...
        'snr', [30], ...
        'max_cases', 6, ...
        'run_static', false, ...
        'run_markov', true, ...
        'run_markov_sweep', false, ...
        'markov_modes', {'slow','medium','fast'}, ...
        'markov_nsym', 12000, ...
        'markov_trainLen', 3000, ...
        'markov_twochain', false, ...
        'markov_use_adaptive_tau', false, ...
        'markov_use_transition_gate', false, ...
        'plot', true, ...
        'fig_visible', 'off', ...
        'save_dir', fullfile(root, 'BlockB_c2m_tracking'));
catch ME
    out.blockB_error = ME;
    local_print_error('Block B', ME);
end

try
    fprintf('\n[smoke_figs_v72] Block B tuned two-chain tracking.\n');
    out.blockB_tuned = run_paper('8023ck_sparam', ...
        'trials', 1, ...
        'snr', [30], ...
        'max_cases', 6, ...
        'run_static', false, ...
        'run_markov', true, ...
        'run_markov_sweep', false, ...
        'markov_modes', {'slow','medium','fast'}, ...
        'markov_nsym', 12000, ...
        'markov_trainLen', 3000, ...
        'markov_twochain', true, ...
        'markov_twochain_noise_scale', 1.25, ...
        'markov_twochain_imp_prob', 0, ...
        'markov_twochain_imp_alpha', 0, ...
        'markov_use_adaptive_tau', true, ...
        'markov_tau_calib', 0.5, ...
        'markov_use_transition_gate', false, ...
        'plot', true, ...
        'fig_visible', 'off', ...
        'save_dir', fullfile(root, 'BlockB_c2m_twochain_tracking_tuned'));
catch ME
    out.blockB_tuned_error = ME;
    local_print_error('Block B tuned', ME);
end

try
    fprintf('\n[smoke_figs_v72] Block C endogenous-aware family.\n');
    out.blockC = run_paper('endogenous_family', ...
        'trials', 2, ...
        'snr', [15 18 22 26 29], ...
        'plot', true, ...
        'fig_visible', 'off', ...
        'save_dir', fullfile(root, 'BlockC_endogenous_family'));
catch ME
    out.blockC_error = ME;
    local_print_error('Block C', ME);
end

try
    fprintf('\n[smoke_figs_v72] Extra eye/channel-impact figures.\n');
    % The extra-figure script writes to the final pack by design.  Run it
    % once, then copy the visual QA outputs into this smoke folder.
    out.extra = run_final_extra_figures_v72();
    extra_src = fullfile(pwd, 'paper_final_all_blocks_v72', 'ExtraFigures');
    extra_dst = fullfile(root, 'ExtraFigures');
    if exist(extra_src, 'dir')
        if ~exist(extra_dst, 'dir'), mkdir(extra_dst); end
        copyfile(fullfile(extra_src, '*'), extra_dst);
    end
catch ME
    out.extra_error = ME;
    local_print_error('Extra figures', ME);
end

try
    local_write_manifest(root);
catch ME
    local_print_error('Manifest', ME);
end

save(fullfile(root, 'smoke_all_figures_v72.mat'), 'out', '-v7.3');
fprintf('\n[smoke_figs_v72] Finished %s\n', datestr(now));
fprintf('[smoke_figs_v72] Open this folder: %s\n', root);
end

function local_write_manifest(root)
files = dir(fullfile(root, '**', '*.png'));
fid = fopen(fullfile(root, 'figure_manifest.txt'), 'w');
fprintf(fid, 'Smoke figure manifest generated %s\n\n', datestr(now));
for i = 1:numel(files)
    fpath = fullfile(files(i).folder, files(i).name);
    fprintf(fid, '%s\t%d bytes\n', strrep(fpath, root, '.'), files(i).bytes);
end
fclose(fid);
end

function local_print_error(label, ME)
fprintf(2, '\n[smoke_figs_v72] %s failed: %s\n', label, ME.message);
for k = 1:numel(ME.stack)
    fprintf(2, '  %s:%d\n', ME.stack(k).file, ME.stack(k).line);
end
end
