function results = tune_blockB_twochain_strength_v72()
%TUNE_BLOCKB_TWOCHAIN_STRENGTH_V72 Sweep two-chain stress strength.
%   Lightweight search for a final tracking-stress setting where the
%   proposed MSB separates cleanly from single-bank Algorithm 1.

save_root = fullfile(pwd, 'paper_final_all_blocks_v72', 'BlockB_twochain_tune');
if ~exist(save_root, 'dir')
    mkdir(save_root);
end

configs = [ ...
    struct('noise_scale',1.25,'imp_prob',0.0000,'imp_alpha',0.0); ...
    struct('noise_scale',1.50,'imp_prob',0.0000,'imp_alpha',0.0); ...
    struct('noise_scale',1.75,'imp_prob',0.0000,'imp_alpha',0.0); ...
    struct('noise_scale',1.50,'imp_prob',0.0005,'imp_alpha',6.0); ...
    struct('noise_scale',1.75,'imp_prob',0.0005,'imp_alpha',6.0); ...
    struct('noise_scale',2.00,'imp_prob',0.0005,'imp_alpha',6.0); ...
    struct('noise_scale',1.75,'imp_prob',0.0010,'imp_alpha',6.0); ...
    struct('noise_scale',2.00,'imp_prob',0.0010,'imp_alpha',6.0) ...
];

results = repmat(struct('config',[],'out',[],'min_gain_alg1',NaN, ...
    'min_gain_chen',NaN,'slow_gain_alg1',NaN,'medium_gain_alg1',NaN, ...
    'fast_gain_alg1',NaN), numel(configs), 1);

for i = 1:numel(configs)
    c = configs(i);
    out_dir = fullfile(save_root, sprintf('cfg%02d_ns%.2f_ip%.4f_ia%.1f', ...
        i, c.noise_scale, c.imp_prob, c.imp_alpha));
    fprintf('\n[tune_blockB] cfg %d/%d: noise_scale=%.2f, imp_prob=%.4g, imp_alpha=%.1f\n', ...
        i, numel(configs), c.noise_scale, c.imp_prob, c.imp_alpha);

    out = run_paper('8023ck_sparam', ...
        'trials', 3, ...
        'snr', 30, ...
        'max_cases', 6, ...
        'run_static', false, ...
        'run_markov', true, ...
        'run_markov_sweep', false, ...
        'markov_modes', {'slow','medium','fast'}, ...
        'markov_twochain', true, ...
        'markov_twochain_noise_scale', c.noise_scale, ...
        'markov_twochain_imp_prob', c.imp_prob, ...
        'markov_twochain_imp_alpha', c.imp_alpha, ...
        'markov_use_adaptive_tau', false, ...
        'markov_use_transition_gate', false, ...
        'plot', false, ...
        'fig_visible', 'off', ...
        'save_dir', out_dir);

    gains_alg1 = local_gain(out.markov, 'BER_algorithm1');
    gains_chen = local_gain(out.markov, 'BER_chen_pulse_ref');

    results(i).config = c;
    results(i).out = out;
    results(i).min_gain_alg1 = min(gains_alg1);
    results(i).min_gain_chen = min(gains_chen);
    results(i).slow_gain_alg1 = gains_alg1(1);
    results(i).medium_gain_alg1 = gains_alg1(2);
    results(i).fast_gain_alg1 = gains_alg1(3);

    fprintf('[tune_blockB] gains vs Alg1 slow/medium/fast = %.1f%% / %.1f%% / %.1f%% | min vs Chen %.1f%%\n', ...
        100*gains_alg1(1), 100*gains_alg1(2), 100*gains_alg1(3), 100*min(gains_chen));
end

save(fullfile(save_root, 'tune_blockB_twochain_strength_v72.mat'), 'results', '-v7.3');
local_write_summary(fullfile(save_root, 'tune_summary.csv'), results);
end

function gains = local_gain(markov, baseline_field)
gains = nan(1, numel(markov));
for k = 1:numel(markov)
    prop = markov(k).BER_algorithm6;
    base = markov(k).(baseline_field);
    gains(k) = (base - prop) ./ max(base, eps);
end
end

function local_write_summary(path, results)
fid = fopen(path, 'w');
fprintf(fid, 'idx,noise_scale,imp_prob,imp_alpha,min_gain_alg1,min_gain_chen,slow_gain_alg1,medium_gain_alg1,fast_gain_alg1\n');
for i = 1:numel(results)
    c = results(i).config;
    fprintf(fid, '%d,%.6g,%.6g,%.6g,%.12g,%.12g,%.12g,%.12g,%.12g\n', ...
        i, c.noise_scale, c.imp_prob, c.imp_alpha, ...
        results(i).min_gain_alg1, results(i).min_gain_chen, ...
        results(i).slow_gain_alg1, results(i).medium_gain_alg1, results(i).fast_gain_alg1);
end
fclose(fid);
end
