function results = tune_blockB_algo_gate_v72()
%TUNE_BLOCKB_ALGO_GATE_V72 Sweep HMM tau/gate options for Block B stress.

save_root = fullfile(pwd, 'paper_final_all_blocks_v72', 'BlockB_algo_gate_tune');
if ~exist(save_root, 'dir')
    mkdir(save_root);
end

configs = [ ...
    struct('adaptive_tau',false,'tau_calib',1.0,'gate',false,'gate_conf',0.50); ...
    struct('adaptive_tau',true, 'tau_calib',0.5,'gate',false,'gate_conf',0.50); ...
    struct('adaptive_tau',true, 'tau_calib',1.0,'gate',false,'gate_conf',0.50); ...
    struct('adaptive_tau',true, 'tau_calib',2.0,'gate',false,'gate_conf',0.50); ...
    struct('adaptive_tau',false,'tau_calib',1.0,'gate',true, 'gate_conf',0.40); ...
    struct('adaptive_tau',false,'tau_calib',1.0,'gate',true, 'gate_conf',0.50); ...
    struct('adaptive_tau',true, 'tau_calib',0.5,'gate',true, 'gate_conf',0.40); ...
    struct('adaptive_tau',true, 'tau_calib',1.0,'gate',true, 'gate_conf',0.40) ...
];

results = repmat(struct('config',[],'out',[],'min_gain_alg1',NaN, ...
    'min_gain_chen',NaN,'slow_gain_alg1',NaN,'medium_gain_alg1',NaN, ...
    'fast_gain_alg1',NaN), numel(configs), 1);

for i = 1:numel(configs)
    c = configs(i);
    out_dir = fullfile(save_root, sprintf('cfg%02d_tau%d_tc%.1f_gate%d_gc%.2f', ...
        i, c.adaptive_tau, c.tau_calib, c.gate, c.gate_conf));
    fprintf('\n[tune_gate] cfg %d/%d: adaptive_tau=%d tau_calib=%.2f gate=%d gate_conf=%.2f\n', ...
        i, numel(configs), c.adaptive_tau, c.tau_calib, c.gate, c.gate_conf);

    out = run_paper('8023ck_sparam', ...
        'trials', 3, ...
        'snr', 30, ...
        'max_cases', 6, ...
        'run_static', false, ...
        'run_markov', true, ...
        'run_markov_sweep', false, ...
        'markov_modes', {'slow','medium','fast'}, ...
        'markov_twochain', true, ...
        'markov_twochain_noise_scale', 1.25, ...
        'markov_twochain_imp_prob', 0, ...
        'markov_twochain_imp_alpha', 0, ...
        'markov_use_adaptive_tau', c.adaptive_tau, ...
        'markov_tau_calib', c.tau_calib, ...
        'markov_use_transition_gate', c.gate, ...
        'markov_transition_gate_conf', c.gate_conf, ...
        'plot', false, ...
        'fig_visible', 'off', ...
        'save_dir', out_dir);

    gains_alg1 = local_gain(out.markov, 'BER_algorithm1');
    gains_chen = local_gain(out.markov, 'BER_chen_pulse_ref');
    results(i).config = c;
    results(i).out = out;
    results(i).min_gain_alg1 = min(gains_alg1);
    results(i).min_gain_chen = min(gains_chen);
    results(i).slow_gain_alg1 = gains_alg1(1);
    results(i).medium_gain_alg1 = gains_alg1(2);
    results(i).fast_gain_alg1 = gains_alg1(3);

    fprintf('[tune_gate] gains vs Alg1 slow/medium/fast = %.1f%% / %.1f%% / %.1f%% | min vs Chen %.1f%%\n', ...
        100*gains_alg1(1), 100*gains_alg1(2), 100*gains_alg1(3), 100*min(gains_chen));
end

save(fullfile(save_root, 'tune_blockB_algo_gate_v72.mat'), 'results', '-v7.3');
local_write_summary(fullfile(save_root, 'tune_summary.csv'), results);
end

function gains = local_gain(markov, baseline_field)
gains = nan(1, numel(markov));
for k = 1:numel(markov)
    prop = markov(k).BER_algorithm6;
    base = markov(k).(baseline_field);
    gains(k) = (base - prop) ./ max(base, eps);
end
end

function local_write_summary(path, results)
fid = fopen(path, 'w');
fprintf(fid, 'idx,adaptive_tau,tau_calib,gate,gate_conf,min_gain_alg1,min_gain_chen,slow_gain_alg1,medium_gain_alg1,fast_gain_alg1\n');
for i = 1:numel(results)
    c = results(i).config;
    fprintf(fid, '%d,%d,%.6g,%d,%.6g,%.12g,%.12g,%.12g,%.12g,%.12g\n', ...
        i, c.adaptive_tau, c.tau_calib, c.gate, c.gate_conf, ...
        results(i).min_gain_alg1, results(i).min_gain_chen, ...
        results(i).slow_gain_alg1, results(i).medium_gain_alg1, results(i).fast_gain_alg1);
end
fclose(fid);
end
